name: Deploy via SSH
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_IP }}
        username: ${{ secrets.SSH_HOST_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: cd /var/www/html/gigs && git pull && service nginx restart && chown -R www-data:www-data /var/www/html/gigs
